---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "bundle_recognize"
description: Extract bundles from one (or more) tractograms
keywords:
  - Diffusion MRI
  - Tractogram
  - Segmentation
  - Bundles
tools:
  - "Scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - tractograms:
      type: file
      description: Tractogram file(s) for bundle extraction
      pattern: "*.trk"
      mandatory: true

  - transform:
      type: file
      description: Transform matrix bringing the atlas to native space
      pattern: "*.mat"
      mandatory: true

  - config:
      type: file
      description: Bundle atlas configuration file
      pattern: "*.json"
      mandatory: true

  - directory:
      type: directory
      description: Directory containing the reference atlas
      mandatory: true

args:
  - minimal_vote_ratio:
      type: float
      description: |
        The ratio is a value between 0 and 1.
        Ex: If you have 5 input model directories and a minimal_vote_ratio of 0.5, you will need at least 3 votes.
      default: 0.5

  - seed:
      type: int
      description: Seed for random number generator
      default: 0

  - processes:
      type: int
      description: Number of sub-processes to start.
      default: 1

  - outlier_alpha:
      type: float
      description: Percent of the length of the tree that clusters of individual streamlines will be pruned.
      default: 0.6

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - bundles:
      type: file
      description: Segmented and cleaned bundles
      pattern: "*.trk"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@CHrlS98"
