---
name: "utils_templateflow"
description: |
  Module to fetch a population average template from TemplateFlow.
keywords:
  - template
  - population average
  - reference
tools:
  - "TemplateFlow":
      description: |
        TemplateFlow is a modular, version-controlled resource that
        allows researchers to use templates "off-the-shelf".
      homepage: "https://www.templateflow.org/"
      doi: "10.1038/s41592-022-01681-2"

input:
  - template:
      type: file
      description: |
        TemplateFlow template name.
        e.g. `MNI152NLin2009cAsym`
        Refer to the TemplateFlow documentation for available templates.
        https://www.templateflow.org/browse/
      mandatory: true
  - res:
      type: integer
      description: |
        Resolution of the template. This is optional, but will be used to
        fetch the template at the specified resolution and make it
        accessible in the output channels.
      mandatory: false
  - cohort:
      type: integer
      description: |
        Cohort of the template. This is optional, but will be used to fetch
        the template for the specified cohort and make it accessible in the
        output channels.
      mandatory: false

output:
  - folder:
      type: directory
      description: |
        Directory containing the requested template, with all available
        resolutions and masks/maps.
  - T1w:
      type: file
      description: |
        T1w image of the requested template.
  - T2w:
      type: file
      description: |
        T2w image of the requested template.
  - brain_mask:
      type: file
      description: |
        Brain mask of the requested template.
  - label_CSF:
      type: file
      description: |
        CSF probability map of the requested template.
  - label_GM:
      type: file
      description: |
        GM probability map of the requested template.
  - label_WM:
      type: file
      description: |
        WM probability map of the requested template.
  - metadata:
      type: file
      description: |
        Metadata file containing information about the template.
      pattern: "*.json"
  - citations:
      type: file
      description: |
        File containing citations for the template.
      pattern: "*.bib"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
