---
name: "betcrop_synthbet"
description: Perform brain extraction using synthstrip on image
keywords:
  - anatomical image
  - BET
  - freesurfer
tools:
  - "Freesurfer":
      description: "Software package for the analysis and visualization of structural and functional neuroimaging data."
      homepage: "https://surfer.nmr.mgh.harvard.edu/fswiki"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - image:
      type: file
      description: Nifti image volume to perform BET.
      pattern: "*.{nii,nii.gz}"
      mandatory: true

  - weights:
      type: file
      description: Alternative model weights
      pattern: "*.pt"
      mandatory: false

args:
  - gpu:
      type: boolean
      description: Use GPU for synthstrip
      default: false

  - border:
      type: int
      description: Mask border threshold in mm.
      default: 1

  - nocsf:
      type: boolean
      description: Exclude CSF from brain border
      default: false

  - model:
      type: string
      description: |
        Alternative model weights
        (see [https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/](https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/) for a list of available models.
      default: None

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - bet_image:
      type: file
      description: Nifti brain-extracted volume.
      pattern: "*__bet_image.{nii,nii.gz}"

  - brain_mask:
      type: file
      description: Brain-extracted image mask .
      pattern: "*__brain_mask.{nii,nii.gz}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@anroy1"
