---
name: "bundle_fixelafd"
description: USE scilpy to compute mean apparent fiber density (AFD) and mean radial radial fODF (radfODF) maps along a bundle.
keywords:
  - DWI
  - AFD
  - Fixel
tools:
  - "Scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - bundles:
      type: list
      description: "List of bundles in .trk format."
      pattern: "*.trk"
      mandatory: true

  - fodf:
      type: file
      description: "fODF file to extract fixel measurements from."
      pattern: "*.nii.gz"
      mandatory: true

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - fixel_afd:
      type: list
      description: "Mean Apparent Fiber Density (AFD) along the bundle."
      pattern: "*_afd_metric.nii.gz"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@grahamlittlephd"
