---
name: "segmentation_fastsurfer"
description: write your description here
keywords:
  - segmentation
  - fastsurfer
  - deepmi

tools:
  - "Fastsurfer":
      description: "The FastSurfer pipeline consists of two main parts for segmentation and surface reconstruction."
      homepage: "https://github.com/Deep-MI/FastSurfer"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - anat:
      type: file
      description: An anatomy (ex, .nii.gz).
      pattern: "*.{nii,nii.gz,mgz}"

  - fs_license:
      type: file
      description: The path to your FreeSurfer license. To get one, go to https://surfer.nmr.mgh.harvard.edu/registration.html. Optional. If you have already set your license as prescribed by Freesurfer (copied to a .license file in your $FREESURFER_HOME), this is not required.
      pattern: "*.txt"

args:
  - acq3T:
      type: boolean
      description: "Use this flag if the input T1w image was acquired at 3T."
      default: false
  - cerebnet:
      type: boolean
      description: "Use this flag to enable cerebellum sub-segmentation with CerebNet."
      default: false
  - hypvinn:
      type: boolean
      description: "Use this flag to enable hypothalamus sub-segmentation with HypVinn."
      default: false
  - seg_only:
      type: boolean
      description: |
        Use this flag to only run the segmentation part of FastSurfer. If false, will also
        run the surface reconstruction part (recon-surf).
      default: true

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - fastsurferdirectory:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@arnaudbore"
maintainers:
  - "@arnaudbore"
