name: Deploy documentation

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
      - dev

jobs:
  build-only:
    if: github.event_name == 'pull_request_target'
    uses: scilus/nf-pediatric-documentation/.github/workflows/deploy.yml@main
    with:
      deploy: false
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit

  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: scilus/nf-pediatric-documentation/.github/workflows/deploy.yml@main
    with:
      deploy: true
    secrets: inherit
